var data = {};

data['lexer'] = [
    { code: "abap", name: "ABAP" },
    { code: "as", name: "ActionScript" },
    { code: "as3", name: "ActionScript 3" },
    { code: "ada", name: "Ada" },
    { code: "antlr", name: "ANTLR" },
    { code: "antlr-as", name: "ANTLR With ActionScript Target" },
    { code: "antlr-csharp", name: "ANTLR With C# Target" },
    { code: "antlr-cpp", name: "ANTLR With CPP Target" },
    { code: "antlr-java", name: "ANTLR With Java Target" },
    { code: "antlr-objc", name: "ANTLR With ObjectiveC Target" },
    { code: "antlr-perl", name: "ANTLR With Perl Target" },
    { code: "antlr-python", name: "ANTLR With Python Target" },
    { code: "antlr-ruby", name: "ANTLR With Ruby Target" },
    { code: "apacheconf", name: "ApacheConf" },
    { code: "applescript", name: "AppleScript" },
    { code: "aspectj", name: "AspectJ" },
    { code: "aspx-cs", name: "aspx-cs" },
    { code: "aspx-vb", name: "aspx-vb" },
    { code: "asy", name: "Asymptote" },
    { code: "ahk", name: "autohotkey" },
    { code: "autoit", name: "AutoIt" },
    { code: "awk", name: "Awk" },
    { code: "basemake", name: "Base Makefile" },
    { code: "bash", name: "Bash" },
    { code: "console", name: "Bash Session" },
    { code: "bat", name: "Batchfile" },
    { code: "bbcode", name: "BBCode" },
    { code: "befunge", name: "Befunge" },
    { code: "blitzmax", name: "BlitzMax" },
    { code: "boo", name: "Boo" },
    { code: "brainfuck", name: "Brainfuck" },
    { code: "bro", name: "Bro" },
    { code: "bugs", name: "BUGS" },
    { code: "c", name: "C" },
    { code: "csharp", name: "C#" },
    { code: "cpp", name: "C++" },
    { code: "c-objdump", name: "c-objdump" },
    { code: "ca65", name: "ca65" },
    { code: "cbmbas", name: "CBM BASIC V2" },
    { code: "ceylon", name: "Ceylon" },
    { code: "cfengine3", name: "CFEngine3" },
    { code: "cfs", name: "cfstatement" },
    { code: "cheetah", name: "Cheetah" },
    { code: "clojure", name: "Clojure" },
    { code: "cmake", name: "CMake" },
    { code: "cobol", name: "COBOL" },
    { code: "cobolfree", name: "COBOLFree" },
    { code: "coffee-script", name: "CoffeeScript" },
    { code: "cfm", name: "Coldfusion HTML" },
    { code: "common-lisp", name: "Common Lisp" },
    { code: "coq", name: "Coq" },
    { code: "cpp-objdump", name: "cpp-objdump" },
    { code: "croc", name: "Croc" },
    { code: "css", name: "CSS" },
    { code: "css+django", name: "CSS+Django/Jinja" },
    { code: "css+genshitext", name: "CSS+Genshi Text" },
    { code: "css+lasso", name: "CSS+Lasso" },
    { code: "css+mako", name: "CSS+Mako" },
    { code: "css+myghty", name: "CSS+Myghty" },
    { code: "css+php", name: "CSS+PHP" },
    { code: "css+erb", name: "CSS+Ruby" },
    { code: "css+smarty", name: "CSS+Smarty" },
    { code: "cuda", name: "CUDA" },
    { code: "cython", name: "Cython" },
    { code: "d", name: "D" },
    { code: "d-objdump", name: "d-objdump" },
    { code: "dpatch", name: "Darcs Patch" },
    { code: "dart", name: "Dart" },
    { code: "control", name: "Debian Control file" },
    { code: "sourceslist", name: "Debian Sourcelist" },
    { code: "delphi", name: "Delphi" },
    { code: "dg", name: "dg" },
    { code: "diff", name: "Diff" },
    { code: "django", name: "Django/Jinja" },
    { code: "dtd", name: "DTD" },
    { code: "duel", name: "Duel" },
    { code: "dylan", name: "Dylan" },
    { code: "dylan-console", name: "Dylan session" },
    { code: "dylan-lid", name: "DylanLID" },
    { code: "ec", name: "eC" },
    { code: "ecl", name: "ECL" },
    { code: "elixir", name: "Elixir" },
    { code: "iex", name: "Elixir iex session" },
    { code: "ragel-em", name: "Embedded Ragel" },
    { code: "erb", name: "ERB" },
    { code: "erlang", name: "Erlang" },
    { code: "erl", name: "Erlang erl session" },
    { code: "evoque", name: "Evoque" },
    { code: "factor", name: "Factor" },
    { code: "fancy", name: "Fancy" },
    { code: "fan", name: "Fantom" },
    { code: "felix", name: "Felix" },
    { code: "fortran", name: "Fortran" },
    { code: "Clipper", name: "FoxPro" },
    { code: "fsharp", name: "FSharp" },
    { code: "gas", name: "GAS" },
    { code: "genshi", name: "Genshi" },
    { code: "genshitext", name: "Genshi Text" },
    { code: "pot", name: "Gettext Catalog" },
    { code: "Cucumber", name: "Gherkin" },
    { code: "glsl", name: "GLSL" },
    { code: "gnuplot", name: "Gnuplot" },
    { code: "go", name: "Go" },
    { code: "gooddata-cl", name: "GoodData-CL" },
    { code: "gosu", name: "Gosu" },
    { code: "gst", name: "Gosu Template" },
    { code: "groff", name: "Groff" },
    { code: "groovy", name: "Groovy" },
    { value: "haml", name: "Haml" },
    { code: "haskell", name: "Haskell" },
    { code: "hx", name: "haXe" },
    { code: "html", name: "HTML" },
    { code: "html+cheetah", name: "HTML+Cheetah" },
    { code: "html+django", name: "HTML+Django/Jinja" },
    { code: "html+evoque", name: "HTML+Evoque" },
    { code: "html+genshi", name: "HTML+Genshi" },
    { code: "html+lasso", name: "HTML+Lasso" },
    { code: "html+mako", name: "HTML+Mako" },
    { code: "html+myghty", name: "HTML+Myghty" },
    { code: "html+php", name: "HTML+PHP" },
    { code: "html+smarty", name: "HTML+Smarty" },
    { code: "html+velocity", name: "HTML+Velocity" },
    { code: "http", name: "HTTP" },
    { code: "haxeml", name: "Hxml" },
    { code: "hybris", name: "Hybris" },
    { code: "idl", name: "IDL" },
    { code: "ini", name: "INI" },
    { code: "io", name: "Io" },
    { code: "ioke", name: "Ioke" },
    { code: "irc", name: "IRC logs" },
    { code: "jade", name: "Jade" },
    { code: "jags", name: "JAGS" },
    { code: "java", name: "Java" },
    { code: "jsp", name: "Java Server Page" },
    { code: "js", name: "JavaScript" },
    { code: "js+cheetah", name: "JavaScript+Cheetah" },
    { code: "js+django", name: "JavaScript+Django/Jinja" },
    { code: "js+genshitext", name: "JavaScript+Genshi Text" },
    { code: "js+lasso", name: "JavaScript+Lasso" },
    { code: "js+mako", name: "JavaScript+Mako" },
    { code: "js+myghty", name: "JavaScript+Myghty" },
    { code: "js+php", name: "JavaScript+PHP" },
    { code: "js+erb", name: "JavaScript+Ruby" },
    { code: "js+smarty", name: "JavaScript+Smarty" },
    { code: "json", name: "JSON" },
    { code: "julia", name: "Julia" },
    { code: "jlcon", name: "Julia console" },
    { code: "kconfig", name: "Kconfig" },
    { code: "koka", name: "Koka" },
    { code: "kotlin", name: "Kotlin" },
    { code: "lasso", name: "Lasso" },
    { code: "lighty", name: "Lighttpd configuration file" },
    { code: "lhs", name: "Literate Haskell" },
    { code: "live-script", name: "LiveScript" },
    { code: "llvm", name: "LLVM" },
    { code: "logos", name: "Logos" },
    { code: "logtalk", name: "Logtalk" },
    { code: "lua", name: "Lua" },
    { code: "make", name: "Makefile" },
    { code: "mako", name: "Mako" },
    { code: "maql", name: "MAQL" },
    { code: "mason", name: "Mason" },
    { code: "matlab", name: "Matlab" },
    { code: "matlabsession", name: "Matlab session" },
    { code: "minid", name: "MiniD" },
    { code: "modelica", name: "Modelica" },
    { code: "modula2", name: "Modula-2" },
    { code: "trac-wiki", name: "MoinMoin/Trac Wiki markup" },
    { code: "monkey", name: "Monkey" },
    { code: "moocode", name: "MOOCode" },
    { code: "moon", name: "MoonScript" },
    { code: "mscgen", name: "Mscgen" },
    { code: "mupad", name: "MuPAD" },
    { code: "mxml", name: "MXML" },
    { code: "myghty", name: "Myghty" },
    { code: "mysql", name: "MySQL" },
    { code: "nasm", name: "NASM" },
    { code: "nemerle", name: "Nemerle" },
    { code: "newlisp", name: "NewLisp" },
    { code: "newspeak", name: "Newspeak" },
    { code: "nginx", name: "Nginx configuration file" },
    { code: "nimrod", name: "Nimrod" },
    { code: "nsis", name: "NSIS" },
    { code: "numpy", name: "NumPy" },
    { code: "objdump", name: "objdump" },
    { code: "objective-c", name: "Objective-C" },
    { code: "objective-c++", name: "Objective-C++" },
    { code: "objective-j", name: "Objective-J" },
    { code: "ocaml", name: "OCaml" },
    { code: "octave", name: "Octave" },
    { code: "ooc", name: "Ooc" },
    { code: "opa", name: "Opa" },
    { code: "openedge", name: "OpenEdge ABL" },
    { code: "perl", name: "Perl" },
    { code: "php", name: "PHP" },
    { code: "plpgsql", name: "PL/pgSQL" },
    { code: "psql", name: "PostgreSQL console (psql)" },
    { code: "postgresql", name: "PostgreSQL SQL dialect" },
    { code: "postscript", name: "PostScript" },
    { code: "pov", name: "POVRay" },
    { code: "powershell", name: "PowerShell" },
    { code: "prolog", name: "Prolog" },
    { code: "properties", name: "Properties" },
    { code: "protobuf", name: "Protocol Buffer" },
    { code: "puppet", name: "Puppet" },
    { code: "pypylog", name: "PyPy Log" },
    { code: "python", name: "Python" },
    { code: "python3", name: "Python 3" },
    { code: "py3tb", name: "Python 3.0 Traceback" },
    { code: "pycon", name: "Python console session" },
    { code: "pytb", name: "Python Traceback" },
    { code: "qml", name: "QML" },
    { code: "racket", name: "Racket" },
    { code: "ragel", name: "Ragel" },
    { code: "ragel-c", name: "Ragel in C Host" },
    { code: "ragel-cpp", name: "Ragel in CPP Host" },
    { code: "ragel-d", name: "Ragel in D Host" },
    { code: "ragel-java", name: "Ragel in Java Host" },
    { code: "ragel-objc", name: "Ragel in Objective C Host" },
    { code: "ragel-ruby", name: "Ragel in Ruby Host" },
    { code: "raw", name: "Raw token data" },
    { code: "rconsole", name: "RConsole" },
    { code: "rd", name: "Rd" },
    { code: "rebol", name: "REBOL" },
    { code: "redcode", name: "Redcode" },
    { code: "registry", name: "reg" },
    { code: "rst", name: "reStructuredText" },
    { code: "rhtml", name: "RHTML" },
    { code: "RobotFramework", name: "RobotFramework" },
    { code: "spec", name: "RPMSpec" },
    { code: "rb", name: "Ruby" },
    { code: "rbcon", name: "Ruby irb session" },
    { code: "rust", name: "Rust" },
    { code: "splus", name: "S" },
    { code: "sass", name: "Sass" },
    { code: "scala", name: "Scala" },
    { code: "ssp", name: "Scalate Server Page" },
    { code: "scaml", name: "Scaml" },
    { code: "scheme", name: "Scheme" },
    { code: "scilab", name: "Scilab" },
    { code: "scss", name: "SCSS" },
    { code: "shell-session", name: "Shell Session" },
    { code: "smali", name: "Smali" },
    { code: "smalltalk", name: "Smalltalk" },
    { code: "smarty", name: "Smarty" },
    { code: "snobol", name: "Snobol" },
    { code: "sp", name: "SourcePawn" },
    { code: "sql", name: "SQL" },
    { code: "sqlite3", name: "sqlite3con" },
    { code: "squidconf", name: "SquidConf" },
    { code: "stan", name: "Stan" },
    { code: "sml", name: "Standard ML" },
    { code: "systemverilog", name: "systemverilog" },
    { code: "tcl", name: "Tcl" },
    { code: "tcsh", name: "Tcsh" },
    { code: "tea", name: "Tea" },
    { code: "tex", name: "TeX" },
    { code: "text", name: "Text only" },
    { code: "treetop", name: "Treetop" },
    { code: "ts", name: "TypeScript" },
    { code: "urbiscript", name: "UrbiScript" },
    { code: "vala", name: "Vala" },
    { code: "vb.net", name: "VB.net" },
    { code: "velocity", name: "Velocity" },
    { code: "verilog", name: "verilog" },
    { code: "vgl", name: "VGL" },
    { code: "vhdl", name: "vhdl" },
    { code: "vim", name: "VimL" },
    { code: "xml", name: "XML" },
    { code: "xml+cheetah", name: "XML+Cheetah" },
    { code: "xml+django", name: "XML+Django/Jinja" },
    { code: "xml+evoque", name: "XML+Evoque" },
    { code: "xml+lasso", name: "XML+Lasso" },
    { code: "xml+mako", name: "XML+Mako" },
    { code: "xml+myghty", name: "XML+Myghty" },
    { code: "xml+php", name: "XML+PHP" },
    { code: "xml+erb", name: "XML+Ruby" },
    { code: "xml+smarty", name: "XML+Smarty" },
    { code: "xml+velocity", name: "XML+Velocity" },
    { code: "xquery", name: "XQuery" },
    { code: "xslt", name: "XSLT" },
    { code: "xtend", name: "Xtend" },
    { code: "yaml", name: "YAML" }
];

data['style'] = [
    { code: "autumn", name: "autumn" },
    { code: "borland", name: "borland" },
    { code: "bw", name: "bw" },
    { code: "colorful", name: "colorful" },
    { code: "default", name: "default" },
    { code: "emacs", name: "emacs" },
    { code: "friendly", name: "friendly" },
    { code: "fruity", name: "fruity" },
    { code: "manni", name: "manni" },
    { code: "monokai", name: "monokai" },
    { code: "murphy", name: "murphy" },
    { code: "native", name: "native" },
    { code: "pastie", name: "pastie" },
    { code: "perldoc", name: "perldoc" },
    { code: "rrt", name: "rrt" },
    { code: "tango", name: "tango" },
    { code: "trac", name: "trac" },
    { code: "vim", name: "vim" },
    { code: "vs", name: "vs" }
];
